# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '/Users/vsts/agent/2.150.3/work/1/s'
    ArtifactName: 'working'
    ArtifactType: 'FilePath'
- task: Xcode@5
  inputs:
    actions: 'clean build'
    scheme: 'helloworld'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

